[package]
name = "chip8-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
itertools = "0.14.0"
nutype = { version = "0.6.2", features = ["new_unchecked"] }
rand = "0.9.2"
thiserror = "2.0.16"

[dev-dependencies]
proptest = "1.8.0"
