name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy # Optional: specify desired components
        override: true # Set this to true to make nightly the default for the current directory
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install apt packages
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
