name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        cache-targets: true
        cache-on-failure: true
    
    - name: Install apt packages
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1

  doc_coverage:
    name: Generate doc-cov badge
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true
          cache-on-failure: true
      
      - name: Install apt packages
        run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
      
      - id: coverage
        uses: bewee/rustdoc-coverage-action@v1
      - run: echo ${{ steps.coverage.outputs.documented }}
      
      - name: Create documentation coverage
        if: github.ref == 'refs/heads/master'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f285310eb2aa23028f1ffa5b6a740d14
          filename: doc-coverage.json
          label: Docs
          message: ${{ steps.coverage.outputs.documented }}
          color: green
          forceUpdate: true
    
  test_coverage:
    name: Generate test-cov badge
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true
          cache-on-failure: true
      
      - name: Install apt packages
        run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov
      - name: Generate lcov.info
        run: |
          cargo llvm-cov \
            --all-features --workspace \
            --lcov --output-path lcov.info \
            -- --test-threads=1

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: lcov.info
  
  deploy_docs:
    name: Deploy github pages docs
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Install apt packages
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

    - name: Build docs
      run: cargo doc --no-deps

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
